<?php
// Part: Flexible Content. One block per layout in acf-json/group_tvbc_page.json (generated by tools/build_acf_json.py).
// The posts page (News) reads the page it is assigned to.
$flex_post_id = is_home() ? (int) get_option( 'page_for_posts' ) : get_the_ID();

if ( function_exists( 'have_rows' ) && have_rows( 'flex_content', $flex_post_id ) ) :

	$i = 0;
	while ( have_rows( 'flex_content', $flex_post_id ) ) :
		the_row();
		$i++;
		$layout = get_row_layout();
		$bg     = tvbc_bg_class( get_sub_field( 'bg' ) );
		$sid    = tvbc_section_id( $i );

		// Heading and text
		if ( 'intro' === $layout ) :
			$text = get_sub_field( 'text' );
			?>
			<section id="<?php echo esc_attr( $sid ); ?>" class="section intro <?php echo esc_attr( $bg ); ?>">
				<div class="container">
					<?php tvbc_section_head(); ?>
					<?php if ( $text ) : ?><div class="intro__text prose"><?php echo tvbc_rich( $text ); // phpcs:ignore ?></div><?php endif; ?>
					<?php $b = tvbc_btn( get_sub_field( 'button_label' ), get_sub_field( 'button_link' ), 'main' ); if ( $b ) : ?><div class="section__actions"><?php echo $b; // phpcs:ignore ?></div><?php endif; ?>
				</div>
			</section>

		<?php
		// Text and photo
		elseif ( 'feature' === $layout ) :
			$photo   = get_sub_field( 'photo' );
			$side    = get_sub_field( 'photo_side' ) === 'left' ? 'left' : 'right';
			$bullets = get_sub_field( 'bullets' );
			?>
			<section id="<?php echo esc_attr( $sid ); ?>" class="section feature feature--<?php echo esc_attr( $side ); ?> <?php echo esc_attr( $bg ); ?>">
				<div class="container feature__inner">
					<div class="feature__copy">
						<?php tvbc_section_head(); ?>
						<?php $t = get_sub_field( 'text' ); if ( $t ) : ?><div class="prose"><?php echo tvbc_rich( $t ); // phpcs:ignore ?></div><?php endif; ?>
						<?php if ( $bullets ) : ?>
							<ul class="ticks"><?php foreach ( $bullets as $b ) : ?><li><?php echo tvbc_inline( $b['line'] ); ?></li><?php endforeach; ?></ul>
						<?php endif; ?>
						<?php $b = tvbc_btn( get_sub_field( 'button_label' ), get_sub_field( 'button_link' ), 'main' ); if ( $b ) : ?><div class="section__actions"><?php echo $b; // phpcs:ignore ?></div><?php endif; ?>
					</div>
					<?php if ( $photo ) : ?><div class="feature__photo"><?php echo tvbc_img( $photo, 'feature__img' ); // phpcs:ignore ?></div><?php endif; ?>
				</div>
			</section>

		<?php
		// Numbered list
		elseif ( 'numbered_list' === $layout ) :
			$items = get_sub_field( 'items' );
			?>
			<section id="<?php echo esc_attr( $sid ); ?>" class="section numbered <?php echo esc_attr( $bg ); ?>">
				<div class="container">
					<?php tvbc_section_head(); ?>
					<?php if ( $items ) : ?>
						<ol class="numbered__list">
							<?php foreach ( $items as $n => $it ) : ?>
								<li class="numbered__item">
									<span class="numbered__num" aria-hidden="true"><?php echo esc_html( str_pad( $n + 1, 2, '0', STR_PAD_LEFT ) ); ?></span>
									<h3 class="numbered__title"><?php echo tvbc_inline( $it['title'] ); ?></h3>
									<?php if ( ! empty( $it['text'] ) ) : ?><div class="numbered__text"><?php echo tvbc_rich( $it['text'] ); // phpcs:ignore ?></div><?php endif; ?>
									<?php $l = tvbc_btn( $it['link_label'], $it['link'], 'plain' ); if ( $l ) : ?><p class="numbered__link"><?php echo $l; // phpcs:ignore ?></p><?php endif; ?>
								</li>
							<?php endforeach; ?>
						</ol>
					<?php endif; ?>
				</div>
			</section>

		<?php
		// Cards
		elseif ( 'cards' === $layout ) :
			$items = get_sub_field( 'items' );
			$cols  = (int) get_sub_field( 'columns' ) ?: 3;
			?>
			<section id="<?php echo esc_attr( $sid ); ?>" class="section cards <?php echo esc_attr( $bg ); ?>">
				<div class="container">
					<?php tvbc_section_head(); ?>
					<?php if ( $items ) : ?>
						<ul class="cards__grid cards__grid--<?php echo esc_attr( $cols ); ?>">
							<?php foreach ( $items as $it ) : ?>
								<li class="card<?php echo ! empty( $it['flag'] ) ? ' card--flagged' : ''; ?>">
									<div class="card__top">
										<?php if ( ! empty( $it['label'] ) ) : ?><span class="card__label"><?php echo tvbc_inline( $it['label'] ); ?></span><?php endif; ?>
										<?php if ( ! empty( $it['flag'] ) ) : ?><span class="flag"><?php echo esc_html( $it['flag'] ); ?></span><?php endif; ?>
									</div>
									<h3 class="card__title"><?php echo tvbc_inline( $it['title'] ); ?></h3>
									<?php if ( ! empty( $it['text'] ) ) : ?><div class="card__text"><?php echo tvbc_rich( $it['text'] ); // phpcs:ignore ?></div><?php endif; ?>
									<?php $l = tvbc_btn( $it['link_label'], $it['link'], 'plain' ); if ( $l ) : ?><p class="card__link"><?php echo $l; // phpcs:ignore ?></p><?php endif; ?>
								</li>
							<?php endforeach; ?>
						</ul>
					<?php endif; ?>
				</div>
			</section>

		<?php
		// Coaches and staff
		elseif ( 'people' === $layout ) :
			$args = array( 'post_type' => 'coach', 'posts_per_page' => -1, 'orderby' => array( 'menu_order' => 'ASC', 'title' => 'ASC' ), 'no_found_rows' => true );
			$pick = get_sub_field( 'pick' );
			if ( 'pick' === get_sub_field( 'source' ) && $pick ) {
				$args['post__in'] = $pick;
				$args['orderby']  = 'post__in';
			}
			$people = new WP_Query( $args );
			?>
			<section id="<?php echo esc_attr( $sid ); ?>" class="section people <?php echo esc_attr( $bg ); ?>">
				<div class="container">
					<?php tvbc_section_head(); ?>
					<?php if ( $people->have_posts() ) : ?>
						<ul class="people__grid">
							<?php
							while ( $people->have_posts() ) :
								$people->the_post();
								$bio     = get_field( 'bio', false, false );
								$photo   = get_field( 'photo' );
								$summary = get_field( 'summary' );
								$teams   = get_field( 'teams' );
								?>
								<li class="person<?php echo $photo ? '' : ' person--empty'; ?>">
									<div class="person__photo">
										<?php echo tvbc_pattern( 'person__pattern' ); // phpcs:ignore ?>
										<?php echo tvbc_img( $photo, 'person__img', 'large' ); // phpcs:ignore ?>
									</div>
									<h3 class="person__name"><?php echo tvbc_inline( get_the_title() ); // phpcs:ignore ?></h3>
									<p class="person__role"><?php echo tvbc_inline( get_field( 'role' ) ); ?></p>
									<?php if ( $teams ) : ?><p class="person__teams"><?php echo tvbc_inline( $teams ); ?></p><?php endif; ?>
									<?php if ( $summary ) : ?><div class="person__summary"><?php echo tvbc_rich( $summary ); // phpcs:ignore ?></div><?php endif; ?>
									<?php if ( $bio ) : ?><p class="person__link"><a class="btn btn--plain" href="<?php the_permalink(); ?>"><?php echo esc_html( tvbc_ui( 'read_bio' ) ); ?></a></p><?php endif; ?>
								</li>
							<?php endwhile; wp_reset_postdata(); ?>
						</ul>
					<?php endif; ?>
				</div>
			</section>

		<?php
		// Facts table
		elseif ( 'fact_table' === $layout ) :
			$rows = get_sub_field( 'rows' );
			?>
			<section id="<?php echo esc_attr( $sid ); ?>" class="section facts <?php echo esc_attr( $bg ); ?>">
				<div class="container facts__inner">
					<?php tvbc_section_head(); ?>
					<?php if ( $rows ) : ?>
						<dl class="facts__list">
							<?php foreach ( $rows as $r ) : ?>
								<div class="facts__row">
									<dt class="facts__label"><?php echo tvbc_inline( $r['label'] ); ?></dt>
									<dd class="facts__value">
										<?php echo tvbc_rich( $r['value'] ); // phpcs:ignore ?>
										<?php if ( ! empty( $r['note'] ) ) : ?><p class="facts__note"><?php echo tvbc_inline( $r['note'] ); ?></p><?php endif; ?>
									</dd>
								</div>
							<?php endforeach; ?>
						</dl>
					<?php endif; ?>
				</div>
			</section>

		<?php
		// Dates
		elseif ( 'key_dates' === $layout ) :
			$rows = get_sub_field( 'rows' );
			?>
			<section id="<?php echo esc_attr( $sid ); ?>" class="section dates <?php echo esc_attr( $bg ); ?>">
				<div class="container dates__inner">
					<?php tvbc_section_head(); ?>
					<?php if ( $rows ) : ?>
						<ol class="dates__list">
							<?php foreach ( $rows as $r ) : ?>
								<li class="dates__row">
									<span class="dates__date"><?php echo tvbc_inline( $r['date'] ); ?></span>
									<div class="dates__body">
										<h3 class="dates__title"><?php echo tvbc_inline( $r['title'] ); ?></h3>
										<?php if ( ! empty( $r['text'] ) ) : ?><p class="dates__text"><?php echo tvbc_inline( $r['text'] ); ?></p><?php endif; ?>
									</div>
								</li>
							<?php endforeach; ?>
						</ol>
					<?php endif; ?>
				</div>
			</section>

		<?php
		// Questions and answers
		elseif ( 'faq' === $layout ) :
			$items    = get_sub_field( 'items' );
			$collapse = (bool) get_sub_field( 'collapse' );
			?>
			<section id="<?php echo esc_attr( $sid ); ?>" class="section faq <?php echo esc_attr( $bg ); ?>">
				<div class="container faq__inner">
					<?php tvbc_section_head(); ?>
					<?php if ( $items ) : ?>
						<div class="faq__list">
							<?php foreach ( $items as $it ) : ?>
								<details class="faq__item"<?php echo $collapse ? '' : ' open'; ?>>
									<summary class="faq__q"><?php echo tvbc_inline( $it['question'] ); ?></summary>
									<div class="faq__a"><?php echo tvbc_rich( $it['answer'] ); // phpcs:ignore ?></div>
								</details>
							<?php endforeach; ?>
						</div>
					<?php endif; ?>
				</div>
			</section>

		<?php
		// Latest news
		elseif ( 'news_list' === $layout ) :
			$news = new WP_Query( array( 'post_type' => 'post', 'posts_per_page' => (int) get_sub_field( 'count' ) ?: 6, 'no_found_rows' => true ) );
			?>
			<section id="<?php echo esc_attr( $sid ); ?>" class="section news <?php echo esc_attr( $bg ); ?>">
				<div class="container news__inner">
					<?php tvbc_section_head(); ?>
					<?php if ( $news->have_posts() ) : ?>
						<ul class="news__list">
							<?php while ( $news->have_posts() ) : $news->the_post(); ?>
								<li class="news__item">
									<time class="news__date" datetime="<?php echo esc_attr( get_the_date( 'c' ) ); ?>"><?php echo esc_html( get_the_date( 'M j, Y' ) ); ?></time>
									<div class="news__body">
										<h3 class="news__title"><a href="<?php the_permalink(); ?>"><?php echo tvbc_inline( get_the_title() ); // phpcs:ignore ?></a></h3>
										<p class="news__excerpt"><?php echo tvbc_inline( wp_trim_words( wp_strip_all_tags( get_the_content() ), 28 ) ); ?></p>
									</div>
								</li>
							<?php endwhile; wp_reset_postdata(); ?>
						</ul>
					<?php else : ?>
						<p class="news__empty"><?php echo esc_html( tvbc_ui( 'no_news' ) ); ?></p>
					<?php endif; ?>
				</div>
			</section>

		<?php
		// Call to action
		elseif ( 'callout' === $layout ) :
			$style = get_sub_field( 'style' ) ?: 'dark';
			$btn   = tvbc_btn( get_sub_field( 'button_label' ), get_sub_field( 'button_link' ), 'dark' === $style ? 'sun' : 'main' );
			$text  = get_sub_field( 'text' );
			$big   = get_sub_field( 'detail' );
			?>
			<section id="<?php echo esc_attr( $sid ); ?>" class="callout callout--<?php echo esc_attr( $style ); ?>">
				<?php if ( 'dark' === $style ) { echo tvbc_pattern( 'callout__pattern' ); } // phpcs:ignore ?>
				<div class="container callout__inner">
					<?php if ( get_sub_field( 'eyebrow' ) ) : ?><p class="eyebrow"><?php echo tvbc_inline( get_sub_field( 'eyebrow' ) ); ?></p><?php endif; ?>
					<h2 class="callout__title"><?php echo tvbc_inline( get_sub_field( 'heading' ) ); ?></h2>
					<?php if ( $big && 'helpline' === $style ) : ?><div class="callout__big"><?php echo tvbc_rich( $big ); // phpcs:ignore ?></div><?php endif; ?>
					<?php if ( $text ) : ?><p class="callout__text"><?php echo tvbc_inline( $text ); ?></p><?php endif; ?>
					<?php if ( $btn ) : ?><div class="callout__actions"><?php echo $btn; // phpcs:ignore ?></div><?php endif; ?>
				</div>
			</section>

		<?php endif; ?>

	<?php endwhile; ?>
<?php endif; ?>
